### ISSUE TITLE
Batch correction on TPMs before analysis?

### ISSUE THREAD

**Issue by ahwanpandey** [icbi-lab/immunedeconv#22]
Hello,

I have some RNAseq data from different batches for which the TPMs have been generated and stored in matrix format. Is it necessary to do any sort of batch correction on these TPM values to be able to compare results between samples?

Thanks!

**Comment by grst** [comment]
Hi @ahwanpandey, 

this is a good question. I didn't experiment with it, but here are some thoughts. 

* In theory, EPIC and quanTIseq are robust to batch effects. In practice, I would still be careful. 
* Using a linear batch correction method, that preserves the distribution of the gene expression values should not do any harm to the methods. 

Maybe @FFinotello, can also comment on this. 

If you try it out, let me know your experiences!

**Comment by ahwanpandey** [comment]
Hi @grst, I was planning on analysing them with and without batch correction. But thought I'd ask the developers had any suggestions first.

Thanks for your comment. Ill let keep you updated if I get any interesting results.
