### ISSUE TITLE
error in xcell, expected cell types

### ISSUE THREAD

**Issue by EzicJ** [icbi-lab/immunedeconv#29]
Hi, 
I wanted to run xcell with a specific list of expected cell types, ended up getting the following:

```
xcell <- deconvolute_xcell(tpm_nolog, arrays = F, expected_cell_types = "B-cells")
Error in get_all_children(cell_type, "xcell") : 
  unknown cell type: B-cells

```
Thanks,

Jasko

**Comment by grst** [comment]
Hi Jasko, 

you need to use the cell-types as named by `immundeconv`, see the overview here: 
https://icbi-lab.github.io/immunedeconv/articles/immunedeconv.html#cell-type-re-mapping

Immunedeconv will map them to the original xCell cell-type names. 

Best, 
Gregor
