### ISSUE TITLE
Could data from NanoString be appiled here？ 

### ISSUE THREAD

**Issue by gudeqing** [icbi-lab/immunedeconv#33]
Hi, I wonder to know if data from a panel of NanoString that could only quantify several hundreads of genes would be appropriate here.

**Comment by grst** [comment]
Hi @gudeqing, 

that's an interesting question and I would be interested in experiences with NanoString data myself. 
I can't give a definite answer, but here are some thoughts: 

- In theory, the methods should also work with Nanostring data, given that the signature genes are measured. To my knowledge, it has never been validated, though, so the results must be interpreted very carefully
- I would give MCPcounter a try. It uses only a few, robust marker genes and at least most of them should be quantified by the nanostring immuno-oncology panel. Also, the methodology is quite straightforward, so there is less that can go wrong in comparison with more sophisticated methods such as CIBERSORT. 

Please let me know how it goes! 

Cheers, 
Gregor

**Comment by gudeqing** [comment]
Hi, Gregor,
   MCPcounter does not compute the cell fraction which I am interested in. However,  I tried Epic Web api before, and it warned that only 31(out of 98) signature genes were covered and the results may be skewed.  I did not try quanTIseq yet for failed to install the many needed packages.  Maybe a tailored method need to be developed.

Best regards!
