### ISSUE TITLE
Combining datasets prior to running

### ISSUE THREAD

**Issue by komalsrathi** [icbi-lab/immunedeconv#35]
Hi,

I have two RNA-seq datasets: one is polyA and the other is stranded. Both have some common cancer types so I combine them into a single matrix of common genes prior to running xCell and CIBERSORT (abs.). Do you recommend this approach? If not and if I run these two methods independently on the datasets, would the results from the two datasets be comparable to each other? 

My goal is to create a heatmap of average immune scores per cell type (y-axis) per cancer type (x-axis) after getting the immune scores. 

Please advise.

Thanks
Komal

**Comment by grst** [comment]
For CIBERSORT, you'll get exactly the same results, for xCell different ones. This is also discussed in [our manuscript](https://academic.oup.com/bioinformatics/article/35/14/i436/5529146). 

I don't have experience with stranded data, but as the signatures have been built on polyA RNA-seq data mostly, I would be very careful and not necessarily expect the results to be comparable.

**Comment by komalsrathi** [comment]
Thanks!
