### ISSUE TITLE
Unable to load limSolve.dylib library

### ISSUE THREAD

**Issue by hbeale** [icbi-lab/immunedeconv#37]
I was unable to install using the steps recommended on https://github.com/icbi-lab/immunedeconv

I installed miniconda from the linked site, then ran these commands: 

```
conda create -n deconvolution
conda activate deconvolution
conda install -c bioconda -c conda-forge r-immunedeconv
```

When I ran the conda install command, I got this message: To use the "java" command line tool you need to install a JDK

I installed the JDK and re-ran the conda install command which ran without error. 

I launched R from the command line from within deconvolution environment, and got the following error:
```
> library(immunedeconv)
Loading required package: EPIC
Error: package or namespace load failed for ‘immunedeconv’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/hbeale/opt/miniconda3/envs/deconvolution/lib/R/library/limSolve/libs/limSolve.dylib':
  dlopen(/Users/hbeale/opt/miniconda3/envs/deconvolution/lib/R/library/limSolve/libs/limSolve.dylib, 6): Library not loaded: @rpath/libopenblasp-r0.3.7.dylib
  Referenced from: /Users/hbeale/opt/miniconda3/envs/deconvolution/lib/R/library/limSolve/libs/limSolve.dylib
  Reason: image not found
```

I uninstalled and reinstalled conda immuneconv:

```
conda remove r-immunedeconv
conda install -c bioconda -c conda-forge r-immunedeconv
```
I still get the same error loading immunedeconv in R

**Comment by grst** [comment]
What operating system are you working on?

**Comment by hbeale** [comment]
OSX 10.14.6

**Comment by grst** [comment]
I don't have a mac, so I cannot confirm if it's a general mac problem.

First thing that's weird is that conda shouldn't need java to run. 

For the second problem, you could try to manually install `libopenblas` into the conda env
```console
conda install conda-forge::libopenblas 
```

Otherwise you could just give non-conda way of installing `immunedeconv` a try.

**Comment by hbeale** [comment]
Will do. Thanks!

**Comment by mahermassoud** [comment]
Getting a similar problem when I try to install using conda-forge method. 

```
> library(immunedeconv)
Loading required package: EPIC
Error: package or namespace load failed for ‘immunedeconv’ in library.dynam(lib, package, package.lib):
 shared object ‘lpSolve.dylib’ not found
``` 

and 

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Mojave 10.14.3

Matrix products: default
BLAS/LAPACK: /Users/massoudmaher/miniconda3/envs/deconv/lib/libopenblasp-r0.3.9.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.6.3
```

**Comment by grst** [comment]
Closing this as it doesn't seem to have reappeared recently.
