### ISSUE TITLE
it is very hard to install.

### ISSUE THREAD

**Issue by chadili** [icbi-lab/immunedeconv#38]
I have tried many times, but  i can't install it correctly. I give up. Could you send it to CRAN?

**Comment by grst** [comment]
Can you provide detailed information on what you tried and what error you get? 

Putting in on CRAN does not work, unfortunately, because the package has several dependencies that are not on CRAN.

**Comment by chadili** [comment]
![image](https://user-images.githubusercontent.com/29422996/77515264-2d834380-6eb3-11ea-95f8-f01884951849.png)

**Comment by grst** [comment]
Hi @chadili, 

I'm afraid I need some more additional information. Can you please provide
* The operating system you are working on 
* All commands, step-by-step that you during the installation. 

Best, 
Gregor

**Comment by chadili** [comment]
Thank you a lot. I have reinstalled all the packages. Now it works.

**Comment by grst** [comment]
glad it worked out in the end!
