### ISSUE TITLE
Is it possible to extract cell-type specific expression from my datamatrix?

### ISSUE THREAD

**Issue by klai001** [icbi-lab/immunedeconv#47]
Hi Developers of Immunedeconv
I have a bulk heterogeneous tissue RNAseq(that hasnt been facs sorted at all)
May I know if it Is it possible to extract cell-type specific expression from my datamatrix
after running deconvolve (matrix,method = "quantiseq",tumor = FALSE) successfully?

**Comment by grst** [comment]
Hi klai001, 

thanks for your question. 
If I got you right, what you want to do is "complete" deconvolution. 
The methods in `immunedeconv` only support "partial" deconvolution -- so no, this is not possible. 

You might want to have a look at the new [CIBERSORTx](https://cibersortx.stanford.edu/) method for that. 

Cheers, 
Gregor

**Comment by klai001** [comment]
Hi Gregor 
thank you for the tips!
Would we then be able to retrieve the gene signatures for each method we run through immunedeconv into a vector?

**Comment by grst** [comment]
With "gene signatures", are you referring to the signature matrices? 

The quantiseq and EPIC signatures are [here](https://github.com/icbi-lab/quanTIseq/blob/master/quantiseq/deconvolution/TIL10_signature.txt) and [here](https://github.com/GfellerLab/EPIC/tree/master/data), respectively. The CIBERSORT matrix is only available upon registration from their website. 

The other methods use different approaches altogether... See our [paper[(https://academic.oup.com/bioinformatics/article/35/14/i436/5529146#137497287) for more details.

**Comment by klai001** [comment]
Yep, Thanks for the materials Gregor!
