### ISSUE TITLE
Cannot install with remotes::install_github("icbi-lab/immunedeconv")

### ISSUE THREAD

**Issue by yoshihiko1218** [icbi-lab/immunedeconv#53]
Hi developer,

When I try remotes::install_github("icbi-lab/immunedeconv"), it will tell me 
Downloading GitHub repo icbi-lab/immunedeconv@HEAD
Error: Failed to install 'immunedeconv' from GitHub:
  incomplete block on file
I am using R version 4.0.2 and connecting from China but using VPN. I have 2GB free space in my hard drive and I think it should be enough?

**Comment by grst** [comment]
Hi @yoshihiko1218, 

sounds like the download did not work. 

Could you try: 
 * `Sys.setlocale(category = "LC_ALL", locale = "us")` and then try again? 
 
If that does not work: 
* download the tar.gz file manually (https://github.com/grst/immunedeconv/archive/master.tar.gz).
* and then use, for instance, `devtools::install_local('tarfile.tar.gz')` to install the package.

**Comment by yoshihiko1218** [comment]
Hi it was problem of my network! Finally worked with command. Thank you for fast reply!
