### ISSUE TITLE
cannot install with conda

### ISSUE THREAD

**Issue by antonkulaga** [icbi-lab/immunedeconv#55]
After I install python 3.8 and rstudio via conda in latest Linux Mint I am trying to install r-immunedeconv and I get the following errors both in mamba and conda:

```
package r-immunedeconv-2.0.2-r36_0 requires r-base >=3.6,<3.7.0a0, but none of the providers can be installed
```

**Comment by grst** [comment]
Hi, 

could you please share with me 
 * the command you use to create the environment
 * the output of ` conda config --show channels`

The commit you were referencing should have nothing to do with it. The unreleased commits are actually just some cosmetic changes and don't fix any installation issues. 

In fact, I can install version 2.0.2 with conda just fine, I suspect that you either have the wrong [channel order](https://bioconda.github.io/user/install.html#set-up-channels) or are trying to install immunedeconv into an existing environment that contains conflicting packages.

**Comment by antonkulaga** [comment]
I managed to make it work. The problem was caused by rstudio-server that I included in the environment to have R IDE
