### ISSUE TITLE
Error in deconvolute_cibersort

### ISSUE THREAD

**Issue by huangwb8** [icbi-lab/immunedeconv#60]
When running `deconvolute_cibersort`, some errors appear:
```
assertion failed: CIBERSORT.R is provided
error: exists("cibersort_binary", envir = config_env) is not TRUE
```
It seems that there is no function `cibersort_binary` loaded. Could you please repair this bug? Thanks!

**Comment by grst** [comment]
Hi @huangwb8, 

you'll need to provide the path to the `CIBERSORT.R` file as specified here: 
https://icbi-lab.github.io/immunedeconv/articles/immunedeconv.html#special-case-cibersort

**Comment by huangwb8** [comment]
Thanks! I got it!
