### ISSUE TITLE
Add more recent methods?

### ISSUE THREAD

**Issue by FFinotello** [icbi-lab/immunedeconv#76]
For human data (list to be expandede):

- [ ] [ConsensusTME](https://cancerres.aacrjournals.org/content/79/24/6238)

For mouse data (list to be expandede):

- [ ]  [mMCP-counter](https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-020-00783-w)

**Comment by FFinotello** [comment]
How about [immunostates](https://www.nature.com/articles/s41467-018-07242-6)?

**Comment by grst** [comment]
never mind, the paper I had in mind was actually the ABIS one.

**Comment by grst** [comment]
Closed in #81
