### ISSUE TITLE
Overview of new implementations

### ISSUE THREAD

**Issue by LorenzoMerotto** [icbi-lab/immunedeconv#80]
1) **MOUSE deconvolution**
Each function will return the results in the way they are given by the tool/algorithm
- [x]  deconvolute_mMCPcounter: performs deconvolution with mMCP counter. Data will be log2 scaled by default (log2 = TRUE). 
- [x] deconvolute_seqImmuCC: performs deconvolution with seqImmuCC. Cell fractions can be estimated with SVR-CIBERSORT or LLSR.  
- [x] deconvolute_DCQ: performs deconvolution with DCQ through the ComICS package. The signature matrix is fixed. This function returns all the 207 cell types in the signature matrix. Since DCQ needs to scale the genes, in the default case the parameters are calculated on all samples. Users can also specify a reduced set of samples to consider. Users can specify the number of repeats the DCQ algorithm will make. 
- [x] deconvolute_BASE: performs deconvolution with BASE algorithm. The immune cel compendium required is provided with the package. This function will return the scores for all the 135 cell types in the compendium. The "permutation" parameter can be specified since it affects the quality of estimates but also the runtime. 
- [x] deconvolute_mouse: this function is a wrapper for the previous ones and will return the results in the same form (samples in columns, cell_type as first column). For DCQ and BASE cell types will be combined/reduced using the following functions to match the ones given by the other methods. 
- [x] reduce_cell_type_DCQ: this function aggregates DCQ results
- [x] reduce_cell_type_BASE: this function aggregates BASE results by taking the median score
- [x] Maybe a function to convert mouse genes into human orthologous ones? 

Files to be included: 
- BASE function + signature matrix (~ 30 MB) 
- seqImmuCC function + signature matrix 
- tables with prefixes to proper aggregate DCQ or BASE results
- validation dataset (Wuaiping et al.) 

2) **HUMAN deconvolution**
- [x] deconvolute_ABIS: the code is adapted from the Shiny app 
- [x] deconvolute_consensusTME

**Comment by grst** [comment]
Two more things we need to think of: 

* Could you please check the licenses of the methods, similar to [this table](https://github.com/icbi-lab/immunedeconv#available-methods-licenses-citations)? We need to be careful when including GPL-licensed code directly in the package and we'll need to update that table anyway. 

* We'll need to take care of the dependency management. The package has already (too) many dependencies, and I'm a bit wary including more. Maybe the new packages should become optional dependencies, as Konstantin implemented it for omnideconv. Also all dependencies must be available on [bioconda](https://github.com/bioconda/bioconda-recipes/). If they are not, we'll need to add them. Could you maybe list the links to all packages and check which methods are already available from bioconda?

**Comment by LorenzoMerotto** [comment]
In terms of external dependencies we need to add: 
- mMCP counter
- ComICS  
- ConsensusTME 
None of this packages seems to be available on Bioconda. All the other methods will be added with their source code


**Licenses**
- mMCPcounter: GP-3.0
- seqImmuCC (requires CIBERSORT): CIBERSORT is free for non commercial use, and I am waiting for the authors to confirm the license for the rest
- DCQ (ComICS package): GPL-2.0
- BASE: not specified (source code is attached to the published paper)

- ABIS: GPL-2.0
- ConsensusTME: GPL-3.0

**Comment by LorenzoMerotto** [comment]
Update from the authors: for the BASE algorithm there is no license so we can use it how we want

**Comment by mlist** [comment]
Did they say that we can use it specifically? As I understand it, no license means technically you can not use it at all.

**Comment by LorenzoMerotto** [comment]
@mlist "There is no license for BASE. Feel free to incorporate into your package." This is what they said. 
They probably meant that there was no particular restriction

**Comment by mlist** [comment]
Ok then :)

**Comment by grst** [comment]
@LorenzoMerotto, I thin you addressed all of this in #81? 
Feel free to close the issue!
