### ISSUE TITLE
Addition of two new methods 

### ISSUE THREAD

**Issue by LorenzoMerotto** [icbi-lab/immunedeconv#83]
...

Methods to be added are: 
- [ABIS](https://github.com/giannimonaco/ABIS) : deconvolution of PBMC RNAseq data through ribust linear regression ([ref](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6367568/))
- [ConsensusTME](https://github.com/cansysbio/ConsensusTME) : scoring of immune  cell types in the tumor micro environment. Several sources are combined to generate a consensus gene set. The identified genes are then used with a single sample GSEA to score each of the cell types. ([ref](https://www.biorxiv.org/content/10.1101/437533v2))

**Notes**
- ConsensusTME is a scoring method, meaning that we can compare scores across samples but not across cell types. ABIS allows to make both intra sample and intra subject comparisons. 
Example: when a reference value was provided just for "T cells", for ABIS the sum of CD4, CD8 and Tregs was considered, while for ConsensusTME only the score for CD4 T cells was considered 
- ConsensusTME is tailored for tumor data and requires the specification of the tumor type. ABIS is intended for PBMC data. 
- Overall, ABIS has a good performance on PBMC data (see: Hoek), while ConsensusTME performs quite well on tumor samples

**Comment by LorenzoMerotto** [comment]
**Finotello dataset**
9 PBMC samples

- **ABIS**
![immagine](https://user-images.githubusercontent.com/91564922/146784292-8e1d7ee0-5a0a-4557-9ed2-2d6b048751b7.png)
- **ConsensusTME**
![immagine](https://user-images.githubusercontent.com/91564922/146784362-4db32b3a-6957-42e4-b775-701ea0a6b076.png)

**Comment by LorenzoMerotto** [comment]
**Hoek dataset**
8 PBMC samples

- **ABIS**
![immagine](https://user-images.githubusercontent.com/91564922/146784498-3dc8a220-0192-46c7-b9c9-d7c396761194.png)
- **ConsensusTME**
![immagine](https://user-images.githubusercontent.com/91564922/146784629-4221ccc3-94f4-4d52-81c4-01ce3dd44665.png)

**Comment by LorenzoMerotto** [comment]
**Lung Tumor dataset**
8 samples, tumor type: LUSC

- **ABIS**
![immagine](https://user-images.githubusercontent.com/91564922/146784843-87c1750d-7127-45cc-a7b6-c1c95725098e.png)

- **ConsensusTME**
![immagine](https://user-images.githubusercontent.com/91564922/146784905-a72a11f6-e27a-440f-8573-c616e7f3d898.png)

**Comment by LorenzoMerotto** [comment]
**Melanoma dataset**
32 samples (additional 28 without any reference), tumor type: SKCM

- **ABIS**
![immagine](https://user-images.githubusercontent.com/91564922/146785026-f92a764a-23f0-4446-a51b-cf668e1f1b3d.png)

- **ConsensusTME**
![immagine](https://user-images.githubusercontent.com/91564922/146785102-d3cd6eed-3f3d-4bb0-b88d-38b3e0cead7b.png)

**Comment by zh-zhang1984** [comment]
There is a new method that can be included in the one-in-all package: ImmuCellAI
I am expecting this functionality because I want my pipeline to be completed in R; without need to switch between web service and R. 

Miao YR, Zhang Q, Lei Q, et al. . ImmuCellAI: A unique method for comprehensive T-cell subsets abundance prediction and its application in cancer immunotherapy. Adv Sci (Weinh). 2020;7(7):1902880.

**Comment by mlist** [comment]
It does not look like the code of ImmuCellAI is available.

**Comment by grst** [comment]
Addressed in #81.
